### ISSUE TITLE
Milestone 2 - TO DO LIST

### ISSUE THREAD

**Issue by nrao944** [UBC-MDS/our_changing_world#12]
- [x] Create the two bottom graphs - @johnwslee  
- [x] Create the top chart/figure - @suuuuperNOVA 
- [x] Create interactive dash - @veerupandey 
- [x] Fix the folder structure/Push to Heroku - @veerupandey 
- [x]  README/Reflections/other modifications - @nrao944 
- [x] Submission - @nrao944
