### ISSUE TITLE
Milestone 4 to do list 

### ISSUE THREAD

**Issue by nrao944** [UBC-MDS/our_changing_world#45]
**PYTHON:**
*1. Include at least five improvements to your app (You are welcome to include more). The changes could be: (i) new things explained in the lecture that you would like to add, (ii) comments from the peer review you received, and/or (iii) TA feedback from previous milestones.*
- [x] Heatmap/Correlation plot (both Python and R) - @nrao944 
- [x] World Ranking axis issue (both Python and R) - @johnwslee 
- [x] Backend of map (both R and Python) - @suuuuperNOVA 
- [x] Documentation (Conduct.md) - @suuuuperNOVA 
- [x] README - @nrao944 
- [x] Scroll bars - @veerupandey

Important to: Paste the link to the commits in the submission with a brief description of the change (similar to a meaningful commit message). 

**DEADLINE FOR R: Wednesday end of day**
** DEADLINE FOR PYTHON: Thursday end of day.**

*2. Finish your interactive Dash app with R and ggplotly* @veerupandey*

*3. Deployment on Heroku of R app: Include the link to your deployed dashboard clearly visible near the top of your README* @veerupandey 

*4.   Tie it all together and deliver a production-ready app*
- [x] You should have addressed all your TAs feedback. Either with comments addressing why feedback implementation is not needed or PRs implementing the changes. @suuuuperNOVA 
- [x] Coding component - @veerupandey 

*5. Reflection* @nrao944 
Significant inputs from @johnwslee, @suuuuperNOVA, @veerupandey  

*6. Submission* (To be decided)

**Comment by suuuuperNOVA** [comment]
- py

1. Address backend issue, both py and r - @[commit 3932574](https://github.com/UBC-MDS/our_changing_world/commit/3932574a4ea920a1e292560ccdb6e39bad6248b4)

2. Documentation (Conduct.md) - @[commit 2a4670](https://github.com/UBC-MDS/our_changing_world/commit/2a46706dd9d6933c634544f8dbf17c74e46bb498)

3. Address TA feedback - @[commit f164147](https://github.com/UBC-MDS/our_changing_world/commit/f1641477f1993209565e0ea81ca89dd75ffba4171)  @[commit a71d073](https://github.com/UBC-MDS/our_changing_world/commit/a71d073bc15e786a8438b7c6777d3bfba305b151) 

4. Add reflection - @[commit 71dad91](https://github.com/UBC-MDS/our_changing_world/commit/71dad91ae52e39a78486024885b445868b0eb4b8)

- r

1. Address backend issue, both py and r - @[commit 095afc](https://github.com/UBC-MDS/our_changing_world-R/commit/095afc446f2ee3bbce9c5918dbfc774360d98b1d)

2. Documentation (Conduct.md) - @[commit b8db37](https://github.com/UBC-MDS/our_changing_world-R/commit/b8db3795c54eb569af01a3a5b26a8b390dbf1f2a)

3. Address TA feedback - @[commit 0a5b5e](https://github.com/UBC-MDS/our_changing_world-R/commit/0a5b5e273695c2c4221231778f163752ca971b52) @[commit c1f28cb](https://github.com/UBC-MDS/our_changing_world-R/commit/c1f28cbcfababfb810cef9f3aa458eef5cccacc2) 

4. Change plot color - @[commit e36fe6](https://github.com/UBC-MDS/our_changing_world-R/commit/e36fe662c79d02c8c80ab55c4e474f93dd498ad5)
